### PR TITLE
run kind env on a remote hosted docker

### PR DESCRIPTION
**Pull request by eslutsky**
this change adds some logic to the AIO setup script  `build_and_setup_everything_bazel_manually.sh`, in case REMOTE_DOCKER_HOST is set it will try to connect to the remote host over ssh and install the kind cluster there.

this works with docker only,not with podman.

### CODE REVIEW

**Comment by ahadas** [comment]
@eslutsky the script looks good, maybe besides replacing the hard-coded IP with environment variable but that's minor, but how about adding a readme that includes what you wrote in the description of the PR?

**Comment by eslutsky** [comment]
> @eslutsky the script looks good, maybe besides replacing the hard-coded IP with environment variable but that's minor, but how about adding a readme that includes what you wrote in the description of the PR?
done,
I've removed the redundant script,   and added some logic to the existing build_and_setup_everything_bazel_manually.sh script.
also removed the need for the exposed docker socket by using docker over ssh .

**Comment by eslutsky** [comment]
> > @eslutsky the script looks good, maybe besides replacing the hard-coded IP with environment variable but that's minor, but how about adding a readme that includes what you wrote in the description of the PR?
 I've removed the redundant script,   and added some logic to the existing build_and_setup_everything_bazel_manually.sh script.
 also removed the need for the exposed docker socket by using docker over ssh .

**Review by ahadas — APPROVED** [review]
changed the phrasing in BUILD_AND_INSTALL_FORKLIFT_WITH_BAZEL_ON_KIND.md a bit, other than that, lgtm

**Pull request merged**
