### PR TITLE
introduce nfs server to the CI 

### PR DESCRIPTION
**Pull request by eslutsky**
nfs-server is required for the following components:
- openstack-volume-populator (with csi-driver-nfs) - WIP
- openstack test environment: packstack cinder - #59

### CODE REVIEW

**Review by ahadas — COMMENTED** [review]
this looks ok but as we don't need the nfs share for testing ovirt/vsphere, how about introducing a different deployment per test (osp/ovirt/vsphere) and have it only for osp?

**Comment by eslutsky** [comment]
> this looks ok but as we don't need the nfs share for testing ovirt/vsphere, how about introducing a different deployment per test (osp/ovirt/vsphere) and have it only for osp?

from my offline conversation with @bennyz  , NFS is required by the OSP volume populator  (it need a dynamic volume driver - ie csi-driver-nfs), does it also required by  the ovirt volume populator ?

**Comment by ahadas** [comment]
> from my offline conversation with @bennyz , NFS is required by the OSP volume populator (it need a dynamic volume driver - ie csi-driver-nfs), does it also required by the ovirt volume populator ?

no, it's not required by the ovirt volume populator (in that scenario, ovirt-imageio exposes the image we place within the container image)

**Comment by eslutsky** [comment]
> this looks ok but as we don't need the nfs share for testing ovirt/vsphere, how about introducing a different deployment per test (osp/ovirt/vsphere) and have it only for osp?

do you mean deploy nfs-server on a k8s deployment, not sure this is a good  practice to install  storage service inside the cluster (which is used by a k8s driver) .. but  we can add parameter to the CI that will specify which provider to install , and install NFS on the OSP jobs only.

**Comment by ahadas** [comment]
> but we can add parameter to the CI that will specify which provider to install , and install NFS on the OSP only.

yep, that's what I meant - we can also deploy fakeovirt and imageio only for ovirt (and vcsim only for vmware) - so if we're able to generalize this, we can leverage it for those other cases

**Comment by eslutsky** [comment]
> > but we can add parameter to the CI that will specify which provider to install , and install NFS on the OSP only.
> 
> yep, that's what I meant - we can also deploy fakeovirt and imageio only for ovirt (and vcsim only for vmware) - so if we're able to generalize this, we can leverage it for those other cases

sure, implemented in this PR #59

**Comment by bennyz** [comment]
> > from my offline conversation with @bennyz , NFS is required by the OSP volume populator (it need a dynamic volume driver - ie csi-driver-nfs), does it also required by the ovirt volume populator ?
> 
> no, it's not required by the ovirt volume populator (in that scenario, ovirt-imageio exposes the image we place within the container image)

What I meant was we need it for the target, as we cannot use a static PV

**Comment by eslutsky** [comment]
closing this PR  , its contained in https://github.com/kubev2v/forkliftci/pull/59

**Pull request closed without merging**
